from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from pydantic import BaseModel, Field

from app.schemas.company import CompanyEntity
from app.schemas.enums import ResearchStatus, SourceType


class SubQuery(BaseModel):
    """One retrieval task generated by the QueryPlanner (or the follow-up
    loop). `target_source_types` lets the orchestrator route it to the right
    adapter(s) instead of blasting every subquery at every provider."""

    text: str
    purpose: str  # e.g. "revenue", "risks", "operating_margin"
    target_source_types: list[SourceType] = Field(default_factory=list)
    is_followup: bool = False
    company: str | None = None  # which company (by CompanyEntity.name) this sub-query targets, if known


class ResearchPlan(BaseModel):
    """Structured research plan produced by the QueryPlanner (PRD section 6).

    Fields are intentionally optional beyond `raw_query` - a query like
    "Compare Tesla and NVIDIA" won't have a single `period`, and the planner
    should not force a bad fit.
    """

    raw_query: str
    companies: list[CompanyEntity] = Field(default_factory=list)
    period: str | None = None
    requested_metrics: list[str] = Field(default_factory=list)
    financial_questions: list[str] = Field(default_factory=list)
    qualitative_questions: list[str] = Field(default_factory=list)
    risk_questions: list[str] = Field(default_factory=list)
    required_source_types: list[SourceType] = Field(default_factory=list)
    sub_queries: list[SubQuery] = Field(default_factory=list)
    is_comparison: bool = False


class ResearchRun(BaseModel):
    """Top-level record of one end-to-end research execution. Persisted so
    /research/{id} can be polled and results reproduced."""

    research_run_id: str = Field(default_factory=lambda: f"run_{uuid4().hex[:12]}")
    query: str
    status: ResearchStatus = ResearchStatus.PENDING
    plan: ResearchPlan | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    followup_iterations_used: int = 0
    research_queries_used: int = 0
    error: str | None = None
    # Which version of the pipeline produced this run. Only runs from the
    # current version are reused for a repeated question: version 2 takes
    # figures for companies VeriFi holds from the database; older runs used
    # third-party aggregators and must not be served again.
    pipeline_version: int | None = None
